
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Oct 11 18:02:45 WIB 2017
//----------------------------------------------------

package Tugas2;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ID = 6;
  public static final int RPAREN = 5;
  public static final int error = 1;
  public static final int PLUS = 2;
  public static final int LPAREN = 4;
  public static final int TIMES = 3;
  public static final int EOF = 0;
}

